IsItABangerWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IsItABangerWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

IsItABangerWeb/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IsItABangerWeb.Models;
using IsItABangerWeb.DataAccess;

namespace IsItABangerWeb.Controllers
{
    public class SongsController : Controller
    {
        private BangerDbContext db = new BangerDbContext();

        private readonly IBangerCalculator _bangerCalculator;

        public SongsController() :
            this(new BangerCalculator(new HaverfordBangerStrategy()))
        {

        }

        public SongsController(IBangerCalculator bangerCalculator)
        {
            _bangerCalculator = bangerCalculator;
        }

        // GET: Songs
        public ActionResult Index(string sortBy = "", bool sortAsc = true)
        {
            Func<Song, object> orderBy = null;
            switch (sortBy.ToLower())
            {
                case "song":
                    orderBy = s => s.Name;
                    break;
                case "artist":
                    orderBy = s => s.Artist;
                    break;
                case "bpm":
                    orderBy = s => s.Bpm;
                    break;
                case "drops":
                    orderBy = s => s.Drops;
                    break;
                case "dope":
                    orderBy = s => s.DropsAreDope;
                    break;
                case "acousticinstruments":
                    orderBy = s => s.HasAcousticInstruments;
                    break;
                case "banger":
                    orderBy = s => s.IsItABanger;
                    break;
                default:
                    sortBy = "song";
                    orderBy = s => s.Name;
                    break;
            }

            var songs = sortAsc 
                ? db.Songs.OrderBy(orderBy) 
                : db.Songs.OrderByDescending(orderBy);

            var nextSortDirAsc = new Dictionary<string, bool>
            {
                {"song", true},
                {"artist", true},
                {"bpm", true},
                {"drops", true},
                {"dope", true},
                {"acousticinstruments", true},
                {"banger", true}
            };
            nextSortDirAsc[sortBy.ToLower()] = !sortAsc;

            ViewBag.SortAsc = nextSortDirAsc;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Songs", songs.ToList());
            }

            return View(songs.ToList());
        }

        // POST: Songs/Result
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Result([Bind(Include = "Bpm,Drops,DropsAreDope,HasAcousticInstruments")] NewSongViewModel newSong)
        {
            if (ModelState.IsValid)
            {
                var song = new Song
                {
                    Bpm = newSong.Bpm,
                    Drops = newSong.Drops,
                    DropsAreDope = newSong.DropsAreDope,
                    HasAcousticInstruments = newSong.HasAcousticInstruments
                };
                _bangerCalculator.SetBanger(song);
                return View(song);
            }

            return RedirectToAction("Index", "Home", newSong);
        }

        // POST: Songs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Artist,Bpm,Drops,DropsAreDope,HasAcousticInstruments,IsItABanger")] Song song)
        {
            if (ModelState.IsValid)
            {
                db.Songs.Add(song);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(song);
        }

        //// GET: Songs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Song song = db.Songs.Find(id);
        //    if (song == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(song);
        //}

        //// POST: Songs/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID,Name,Bpm,Drops,DropsAreDope,HasAcousticInstruments")] Song song)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(song).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(song);
        //}

        //// GET: Songs/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Song song = db.Songs.Find(id);
        //    if (song == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(song);
        //}

        //// POST: Songs/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Song song = db.Songs.Find(id);
        //    db.Songs.Remove(song);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IsItABangerWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>

<p class="text-primary">Based on a super rigorous algorithm developed by Tommy Fresh aka Tom Haverford from Parks and Recreation, this site allows you, dear user, 
    to determine whether that song you are listening to is a banger, or if you should throw out your computer (just to be safe).</p>
<p class="text-primary">
    In reality, this site is a playground for my experimentation with some web development technologies. See the source code on my <a href="https://github.com/crejb/IsItABanger">GitHub</a> page, or drop me a line at developmentsofchris(at)gmail.com.
</p>

IsItABangerWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IsItABangerWeb/Views/Home/Index.cshtml
@model IsItABangerWeb.Models.NewSongViewModel

@{
    Layout = "~/Views/Shared/_LayoutFullPage.cshtml";
    ViewBag.Title = "Home Page";
}

@using (Html.BeginForm("Result", "Songs", FormMethod.Post))
{
    
@Html.AntiForgeryToken()
    
<div id="fullpage">
    <div class="section">
        <div class="jumbotron">
            <p class="lead">A series of rigorous tests to answer one simple question...</p>
            <h1>Is It A Banger?</h1>
            <p>
                <a class="btn btn-primary btn-lg margin-right banger-scroll-down">Start the test</a>
                @Html.ActionLink("See the list", "Index", "Songs", null, new { @class = "btn btn-primary btn-lg" })
            </p>
        </div>
    </div>

    <div class="section">
        <div class="jumbotron">
            <h2>How many beats per minute?</h2>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.EditorFor(model => model.Bpm, new { htmlAttributes = new { id="field_bpm", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bpm, "", new { @class = "text-danger" })
            </div>

            <p>
                <a class="btn btn-primary btn-lg margin-right banger-scroll-down" data-banger-valfield="field_bpm">Next</a>
                <a class="btn btn-primary btn-lg banger-scroll-up">Back</a>
            </p>

        </div>
    </div>

    <div class="section">
        <div class="jumbotron">
            <h2>How many drops?</h2>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.EditorFor(model => model.Drops, new { htmlAttributes = new { id = "field_drops", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Drops, "", new { @class = "text-danger" })
            </div>

            <p>
                <a class="btn btn-primary btn-lg margin-right banger-scroll-down" data-banger-valfield="field_drops">Next</a>
                <a class="btn btn-primary btn-lg banger-scroll-up">Back</a>
            </p>
        </div>
    </div>

    <div class="section">
        <div class="jumbotron">
            <h2>Are the drops dope?</h2>
            <div class="form-group">
                @Html.EditorFor(model => model.DropsAreDope, new { htmlAttributes = new { id = "field_dope", @class = "form-control" } })
            </div>

            <p>
                <a class="btn btn-primary btn-lg margin-right banger-scroll-down">Next</a>
                <a class="btn btn-primary btn-lg banger-scroll-up">Back</a>
            </p>

        </div>
    </div>

    <div class="section">
        <div class="jumbotron">
            <h2>Are there any acoustic instruments?</h2>
            <div class="form-group">
                @Html.EditorFor(model => model.HasAcousticInstruments, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            <p>
                <input type="submit" value="Find out if it's a banger..." class="btn btn-primary btn-lg margin-right" />
                <a class="btn btn-primary btn-lg banger-scroll-up">Back</a>
            </p>

        </div>
    </div>
</div>
}